name: Snyk SAST Scan and Evaluation

on: [push, pull_request]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust Node.js version as needed

      - name: Run Snyk SAST Scan
        continue-on-error: true
        run: |
          mkdir -p snyk-results
          # Install Snyk CLI globally
          npm install -g snyk
          # Authenticate Snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}
          # Run Snyk scan and capture exit code
          snyk code test --json-file-output=snyk-results/scan-results.json || echo "Snyk command failed with exit code $?"
          echo "SNYK_EXIT_CODE=$?" >> $GITHUB_ENV

      - name: Check Snyk Results and Evaluate Build Failure
        env:
          SNYK_EXIT_CODE: ${{ env.SNYK_EXIT_CODE }}
          THRESHOLD: ${{ secrets.SNYK_PRIORITY_THRESHOLD || 750 }}
          REPORT: snyk-results/scan-results.json
        run: |
          echo "THRESHOLD=$THRESHOLD" >> $GITHUB_ENV
          echo "violationsFound=false" >> $GITHUB_ENV
          echo "nonIgnoredViolationsFound=false" >> $GITHUB_ENV

          # Handle Snyk exit codes
          case "$SNYK_EXIT_CODE" in
            0)
              echo "✓ Snyk scan completed successfully - no vulnerabilities found"
              if [ -f "$REPORT" ]; then
                echo "Warning: Report file exists but exit code is 0. Checking for inconsistencies..." >&2
                sleep 1 # Add a small delay to ensure the message is fully logged
                # Optionally parse report for inconsistencies
              else
                echo "✓ No issues found above priority score threshold: $THRESHOLD"
              fi
              ;;
            1)
              echo "⚠ Snyk scan completed - vulnerabilities found, proceeding with evaluation"
              if [ -f "$REPORT" ]; then
                echo "Report file found. Parsing for vulnerabilities..."
                HIGH_SEVERITY_COUNT=$(jq '[.vulnerabilities[] | select(.priorityScore > $THRESHOLD and .isIgnored != true)] | length' "$REPORT" --argjson THRESHOLD "$THRESHOLD" || echo 0)
                if [ "$HIGH_SEVERITY_COUNT" -gt 0 ]; then
                  echo "Error: Found $HIGH_SEVERITY_COUNT non-ignored vulnerabilities above threshold $THRESHOLD"
                  exit 1
                else
                  echo "✓ No issues found above priority score threshold: $THRESHOLD"
                fi
              else
                echo "Error: Snyk indicated vulnerabilities but no report generated"
                exit 1
              fi
              ;;
            2)
              echo "Error: Snyk scan failed - please re-run the command or check configuration"
              exit 1
              ;;
            3)
              echo "Error: No supported projects detected by Snyk - code analysis needed"
              exit 1
              ;;
            *)
              echo "Error: Snyk scan failed with unexpected exit code: $SNYK_EXIT_CODE"
              exit 1
              ;;
          esac
